global:
  message: Welcome to Customer service Prod environment!!
server:
  port: 8083
message: Hello from Prod!
spring:
   datasource:
    url: jdbc:mysql://localhost:3306/cust_prod
    username: deva
    password: deva
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
