server:
  port: 8081

spring:
  application:
    name: customer-service-dev

  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: deva

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
