server:
  port: 8082

spring:
  application:
    name: order-service-dev

  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: deva

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
