global:
  message: Welcome to order service dev environment!!
server:
  port: 8084
message: Hello from order dev!
spring:
   datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: deva
    password: deva
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
