global:
  message: Welcome to order service prod environment!!
server:
  port: 8085
message: Hello from order prod!!
spring:
   datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: deva
    password: deva
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
